### ISSUE TITLE
Oxibooru 0.1 Roadmap

### ISSUE THREAD

**Issue by liamw1** [liamw1/oxibooru#1]
- [x] Implement password reset API
- [x] Implement custom avatars
- [x] Calculate md5 checksums for posts
- [x] Compress post signatures
- [x] Create pre-built docker images for server and client
- [x] Make applying migrations to database automatic
- [x] Write szurubooru-to-oxibooru conversion script
- [x] Add more comments and make sure API documentation is up-to-date
- [x] Improve error messages
- [x] Finish szurubooru-to-oxibooru conversion guide
